### ISSUE TITLE
reading overlay identifiers via API

### ISSUE THREAD

**Issue by NothanUmber** [sensel/sensel-api#10]
Sorry if I should have overlooked it, couldn't find a way how to read the magnetic overlay identifiers via API on first sight though. Is this already possible?
Hopefully the overlay markers are available in the store soon, so we can build our own marked overlays!

**Comment by AlexSensel** [comment]
Hi, you are correct that the process of reading the overlay identifiers is currently not documented. We plan to open this up and document it further in the future, but if you would like experiment with it more yourself, you can read registers 0xF2 and 0xF3, which hold the magnetic identifiers. Sorry for the lack of detail at the moment but you can at least use these two registers to identify each of the existing overlays. I will follow up when additional documentation is available.

**Comment by NothanUmber** [comment]
Thanks! Don't have any official overlays yet but when they arrive I'll give it a try.
Particularly looking forward to news how and when we can mark our own overlays!
