### ISSUE TITLE
building C SenselContacts x86 error

### ISSUE THREAD

**Issue by rwebber** [sensel/sensel-api#11]
I can build HelloSensel both x64 and x86
However, SenselContacts will only build as x64
the error given:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'function': cannot convert from 'void *(__cdecl *)()' to 'LPTHREAD_START_ROUTINE'	SenselContacts	C:\mypath\sensel-api\sensel-examples\sensel-c\example-2-contacts\src\main.c	77

**Comment by rwebber** [comment]
Same issue with SenselForces.
Fine as x64, not as x86.

error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'function': cannot convert from 'void *(__cdecl *)()' to 'LPTHREAD_START_ROUTINE'	SenselForces	C:\...\sensel-api\sensel-examples\sensel-c\example-3-forces\src\main.c	82

**Comment by rwebber** [comment]
Should I go back to the OLD c++ sdk?

**Comment by AlexSensel** [comment]
Hello, sorry for the delay and thank you for contacting us. The examples have been updated to fix this issue.
