### ISSUE TITLE
Support for MIDI Polyphonic Expression (MPE)

### ISSUE THREAD

**Issue by jarmitage** [sensel/sensel-api#14]
> MPE is a method of using MIDI which enables multidimensional controllers to control multiple parameters of every note within MPE-compatible software. [..] In normal MIDI, channel-wide messages (such as pitch bend) are applied to all notes being played on a single channel. In MPE, each note is assigned its own channel so that those messages can be applied to each note individually.

Links:
- https://www.midi.org/articles/midi-polyphonic-expression-mpe
- https://support.roli.com/article/what-is-mpe/
- https://github.com/WeAreROLI/mpejs
- https://juce.com/doc/tutorial_mpe_introduction
- https://juce.com/doc/group__juce__audio__basics-mpe

**Comment by nyboer** [comment]
Thanks for the note. Keep your eye out for future releases for our overlays. As for integrating it in the API, it's a worthwhile suggestion - thanks.
