### ISSUE TITLE
Building libsensel for Bela (BeagleBoard)

### ISSUE THREAD

**Issue by jarmitage** [sensel/sensel-api#15]
Hello,

I am attempting to create a demo of Sensel and [Bela](http://bela.io), the open source hardware and software platform for low latency embedded musical instrument design.

The 32-bit `.deb` does not work on Bela because the BeagleBoard has `armhf` hard float architecture (https://wiki.debian.org/ArmHardFloatPort):

```
root@Bela ~/Bela/sensel/sensel-api/sensel-install$ sudo dpkg -i senselliblinux0.8.2-32bit.deb
dpkg: error processing archive senselliblinux0.8.2-32bit.deb (--install):
 package architecture (i386) does not match system (armhf)
Errors were encountered while processing:
 senselliblinux0.8.2-32bit.deb
```

I have tried to build the library manually using this guide: http://blog.bela.io/2017/01/04/using-an-external-library-with-bela/

Since I wanted to build with forces (https://github.com/sensel/sensel-api#build-with-forces - this section of the readme is difficult to understand), the first problem is described by @batchku (https://github.com/sensel/sensel-api/issues/8), that you do not include `sensel_decompress.h` anywhere in this repo apart from inside the pre-built installers. I did what they did and took it from inside `senselliblinux0.8.2-32bit.deb` and defined `SENSEL_PRESSURE = 1` in `sensel.c`.

Then the `make` output is:

```
root@bela ~/Bela/sensel/sensel-api/sensel-lib$ make
rm -f src/*.o
gcc -c -std=c99 -Wall -Werror -fPIC -fvisibility=hidden -Isrc/ -DSENSEL_EXPORTS  -O2   -c -o src/sensel.o src/sensel.c
gcc -c -std=c99 -Wall -Werror -fPIC -fvisibility=hidden -Isrc/ -DSENSEL_EXPORTS  -O2   -c -o src/sensel_register.o src/sensel_register.c
gcc -c -std=c99 -Wall -Werror -fPIC -fvisibility=hidden -Isrc/ -DSENSEL_EXPORTS  -O2   -c -o src/sensel_serial_linux.o src/sensel_serial_linux.c
mkdir -p build/release/nopressure//obj
mv src/sensel.o src/sensel_register.o src/sensel_serial_linux.o build/release/nopressure//obj
gcc -shared -Wl,-soname,libsensel.so -o build/release/nopressure/libsensel.so build/release/nopressure//obj/sensel.o build/release/nopressure//obj/sensel_register.o build/release/nopressure//obj/sensel_serial_linux.o
strip build/release/nopressure/libsensel.so
```

I can't tell if it's outputting to `/nopressure/` because it is failing to include `sensel_decompress.h` or not.

I moved the resulting `libsensel.so` to `/usr/lib` and tried to run an example Bela project with the custom make flags: `CFLAGS=-I/root/Bela/sensel/sensel-lib/src;LDFLAGS=-L/root/Bela/sensel/sensel-lib/build/release/nopressure/libsensel.so;LDLIBS=-lsensel`

However, this project will not run:

```
Linking...
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../lib/libsensel.so: undefined reference to `senselFreeDecompressionHandle'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../lib/libsensel.so: undefined reference to `senselDecompressFrame'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../lib/libsensel.so: undefined reference to `senselInitDecompressionHandle'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../lib/libsensel.so: undefined reference to `senselDecompressionTriggerDetailChange'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/root/Bela/projects/sensel/sensel] Error 1Bela stopped
``` 

To me it seems like `libsensel.so` is not using `sensel_decompress.h` correctly. Help appreciated!

**Comment by giuliomoro** [comment]
do you get exactly the same result when running without `LDLIBS=-lsensel` ? if yes, then try to add `-lsensel` at the end of `LDFLAGS=` instead:

`CFLAGS=-I/root/Bela/sensel/sensel-lib/src;LDFLAGS=-L/root/Bela/sensel/sensel-lib/build/release/nopressure/libsensel.so -lsensel`

**Comment by giuliomoro** [comment]
actually no wait

**Comment by giuliomoro** [comment]
try this:
`CFLAGS=-I/root/Bela/sensel/sensel-lib/src;LDFLAGS=-L/root/Bela/sensel/sensel-lib/build/release/nopressure/ -lsensel`

**Comment by jarmitage** [comment]
Thanks for the suggestion. Unfortunately same output (`undefined reference to...` errors)

**Comment by giuliomoro** [comment]
the README says

> LibSensel contains the main functionality for communicating with Sensel devices, but does not include force frame decompression, which is contained in LibSenselDecompress. Both libraries are included in the installers found in sensel-install, but LibSensel can be recompiled to be a standalone library (no dependencies on LibSenselDecompress) or to replace the existing LibSensel and support force frames.

so it looks like you may need  LibSenselDecompress as well? Also, google and I cannot find `sensel_decompress.h` or the sources for `libsenseldecompress`.

**Comment by jarmitage** [comment]
Yes, and as mentioned in the issue and in https://github.com/sensel/sensel-api/issues/8, `sensel_decompress.h` can only be found inside one of the other installers. I built `libsensel.so` using this file, but I have no `libsenseldecompress`.

**Comment by giuliomoro** [comment]
Then I would suggest you ask @sensel how to build `libsenseldecompress` for `armv7-linux-gnueabihf`.

**Comment by jarmitage** [comment]
I believe that is the question at hand, yes.

**Comment by AlexSensel** [comment]
Hello, thanks for contacting us. The quick answer is to remove the define of SENSEL_PRESSURE from sensel.c. You should then be able to compile the libsensel.so and use it in your project for everything except forces and labels. 

With regards to sensel_decompress, this library is only used to decompress forces and labels from a Sensel Device, it is not necessary for reading contacts and interacting with the Sensel Device. This library is not open source, so we ship a compiled version with the installers. Not defining SENSEL_PRESSURE should handle removing any of the logic necessary so you can build a fully open source version of the API.

We will make sure to add a compiled version of the ARM library to the github within the next week, which will include libsensel.so and lisenseldecompress.so. Thank you for your patience.

**Comment by jarmitage** [comment]
Do I need `sensel_decompress` to receive raw frame data?

Looking forward to trying the new build.

**Comment by conundrumer** [comment]
@AlexSensel Just wondering, why is sensel_decompress not open source? Also, given that this repository is MIT licensed, does that mean we are allowed to distribute the sensel_decompress binaries on their own (vs bundled with the installers)?

**Comment by AlexSensel** [comment]
Hello, thank you for your patience. I have added a build sensel-api that includes sensel_decompress for armhf. This can be found in sensel-install/sensellib0.8.2-arm.deb. sensel_decompress is only required to receive raw force frame data. If you are interested in contact data, you can use the the open source sensel-lib API. With regards to why sensel_decompress is not open source, it currently contains some proprietary compression algorithms, but we are thinking about how we can open source it in the future. Yes, you may distribute the binaries as part of the MIT license. I hope this works for everyone and let us  know if you have any further questions/issues.
