### ISSUE TITLE
senselSetLEDBrightness: strange LED behavior

### ISSUE THREAD

**Issue by conundrumer** [sensel/sensel-api#16]
I'm running the contacts example and the LEDs seem to light up for only one frame after every call to `senselSetLEDBrightness`, then immediately turning off.

Firmware version: 0.14.116 (this is the latest one as of now)

As a sanity check, I changed [these lines](https://github.com/sensel/sensel-api/blob/707ed55a485fa740cee4bb5dcaf70405f7e34bb4/sensel-examples/sensel-c/example-2-contacts/src/main.c#L103-L104) to the following, to make sure the brightness was actually set

```c
unsigned short brightness;
senselGetLEDBrightness(handle, frame->contacts[c].id, &brightness);

unsigned int state = frame->contacts[c].state;
fprintf(stdout, "Contact ID: %d State: %s B: %d \n", frame->contacts[c].id, CONTACT_STATE_STRING[state], brightness);
```

also if I set the brightness to 10 or below, it doesn't light up at all

setting brightness to a low number down to 11 would make the LEDs stay on, but make them appear to blink (at a slower rate the more contacts there are)

**Comment by AlexSensel** [comment]
Hello, thank you for reporting the issue. We have recreated the bug and will release a firmware update in the next week.

**Comment by AlexSensel** [comment]
Hello, we have updated the firmware (currently 0.14.120) so that the LEDs will not experience this issue when in protocol mode (communicating using our API).
