### ISSUE TITLE
Detected force decaying over time

### ISSUE THREAD

**Issue by fabrpece** [sensel/sensel-api#5]
While experimenting with the API and [samples](https://github.com/sensel/sensel-api/tree/master/sensel-examples), I have noticed that the detected forces decay with time. During my tests, when leaving an object on the board, I see the reported forces going down until reaching a stable value which is usually close to zero. The same happens if I repeatedly place the same object on the board. Strangely enough, even when using the same object, the forces reported on contact can greatly vary.

Is this the expected behavior, or do I need to perform some form of calibration?

Thanks!

**Comment by AlexSensel** [comment]
Thank you for reaching out. This is the expected default behavior. By default, we turn on Dynamic Baselining, which removes unintended forces over time in order to prevent spurious contacts. Dynamic Baselining can be enabled (1) and disabled (0) using senselSetDynamicBaselineEnabled in the API. I hope this helps!

**Comment by fabrpece** [comment]
Hi, and thanks a lot for the reply. I have tried to set the DynamicBaseline flag to either on or off, using the function senselSetDynamicBaselineEnabled. I have also used the function senselGetDynamicBaselineEnabled to make sure the flag is set correctly. However, I do not see any change in behavior on the reported forces -- they still decay (fast) with time. 

One thing I should mention is that in my version of the API (the latest available) the default value for the DynamicBaseline flag is 0. Below I report a snippet of code I have used to check the default and set it to 0. 

```
...
// this goes right after a call to senselOpenDeviceByID
//Query default DynamicBaseline flag value
unsigned char val;
senselGetDynamicBaselineEnabled(handle, &val);
fprintf(stdout, "Default Dynamic Baseline: %u\n", val); // this prints 0
//Explicitly set the DynamicBaseline flag value to OFF
val = (unsigned char)0;
senselSetDynamicBaselineEnabled(handle, val);
senselGetDynamicBaselineEnabled(handle, &val);
fprintf(stdout, "Modified Dynamic Baseline: %u\n", val);  // this prints 0
...
```

I am not sure whether there's something wrong in my inititalisation above, or whether I should see decaying forces also when the DynamicBaseline flag is OFF.

Many thanks.

**Comment by AlexSensel** [comment]
Strange, I just did the tests myself and it reported 1 for the default DynamicBaselineEnabled and can turn off the Baseline. Your code appears to be correct so I would recommend the following:
1) Make sure your Sensel Morph is up to date (sensel.com/start/)
2) Make sure you have installed the latest lib installer and have the latest sensel-api.

If you still continue to have issues, please let me know what OS you are using, and whether it is 32 or 64 bit so I can match your set up.

Thank you.

**Comment by fabrpece** [comment]
Hi, and thanks for the prompt reply. Updating thew firmware did the trick!

For reference -- I am using Ubuntu 16.10, 64 bit. I had to update the board under OSX, but that fixed the issue.

Thanks a lot for the support!
