### ISSUE TITLE
Can't get frame rate

### ISSUE THREAD

**Issue by nesdnuma** [sensel/sensel-api#6]
Hello,

I am trying to get the current frame rate using this code:
`senselGetMaxFrameRate(handle, unsigned short val)`
However there is a red wavy underline under the word "unsigned" displayed by VS2015. If I put the mouse pointer there I have a "expression expected" popup. The compiler reports a syntax error. What's wrong?

**Comment by nosuchtim** [comment]
The second argument to that function should be a pointer to an unsigned short, e.g.

unsigned short val;
if ( senselGetMaxFrameRate(handle, &val) == SENSEL_ERROR ) {
    // error handling
}

**Comment by nesdnuma** [comment]
Thanks Tim.

I do not understand neither how to grab the frame rate. According to this...
```
SenselStatus WINAPI senselGetMaxFrameRate(SENSEL_HANDLE handle, unsigned short *val)
{
  return senselReadReg(handle, SENSEL_REG_SCAN_FRAME_RATE, 2, (unsigned char*)val);
}
```

...the function calls another one:
```
SenselStatus WINAPI senselReadReg(SENSEL_HANDLE handle, unsigned char reg, unsigned char size, ```
unsigned char *buf)
{
  SenselDevice *device = (SenselDevice*) handle;

  if (!device)
    return SENSEL_ERROR;

  return _senselReadReg(handle, &device->sensor_serial, reg, size, buf);
}
```
Then, in sensel_register.h, one can find this:
```
SenselStatus _senselReadReg(SENSEL_HANDLE handle, SenselSerialHandle *serial,
                            unsigned char reg, unsigned char size, unsigned char *buf);
```
How do I deal with this?

**Comment by nesdnuma** [comment]
OK, I got it from another source:
```
short maxFrameRate = 0;
SenselStatus resultat = senselGetMaxFrameRate(handle, &maxFrameRate);
if(resultat == SENSEL_OK)
	printf("Max frame rate: %d\n", maxFrameRate);
```
