### ISSUE TITLE
Do senselGetScanDetail and senselSetScanDetail function correctly?

### ISSUE THREAD

**Issue by nesdnuma** [sensel/sensel-api#7]
Hello,

I try to change the scan detail with function senselSetScanDetail(). I have tried all possible values (  SCAN_DETAIL_HIGH, SCAN_DETAIL_MEDIUM, SCAN_DETAIL_LOW). Whatever the value used, I get a Sensel_OK.

However if I use the senselGetScanDetail() function afterwards, I always get the same value (1, that is SCAN_DETAIL_MEDIUM).

What's wrong?

**Comment by AlexSensel** [comment]
Hello, I just confirmed that if you use the following code, then the scan detail value will change. Here is the code I used:
    SenselScanDetail detail = SCAN_DETAIL_HIGH;
    senselSetScanDetail(handle, detail);
    senselGetScanDetail(handle, &detail);
    fprintf(stdout, "Detail: %d\n", detail);
I have not confirmed this, but I believe that the detail level will change back to Medium if you reset the device or stop scanning. Hope this helps.

**Comment by nesdnuma** [comment]
Actually I coded it that way. However I regret that you have closed the issue because things are not so clear: what do you mean with "stop scanning", technically, as there's no "scan" function in the API? When is the "scanning" active? When a device is open??? I guess the issue is there.

**Comment by AlexSensel** [comment]
1) Start scanning: https://github.com/sensel/sensel-api/blob/master/sensel-lib/src/sensel.h#L360
Stop scanning: https://github.com/sensel/sensel-api/blob/master/sensel-lib/src/sensel.h#L368
2) A device is open when you call an open method like senselOpenDeviceByID()
https://github.com/sensel/sensel-api/blob/master/sensel-examples/sensel-c/example-2-contacts/src/main.c#L66
https://github.com/sensel/sensel-api/blob/master/sensel-lib/src/sensel.h#L241

I can provide more assistance if you give code or provide context to where these functions are being called, but I have verified that when the code I provided is pasted here: https://github.com/sensel/sensel-api/blob/master/sensel-examples/sensel-c/example-2-contacts/src/main.c#L67 and in several other places, the code works as expected.

**Comment by nesdnuma** [comment]
All right, I have pasted the startScanning function for so long in my code that I don't even see it anymore! Please accept my apologies.

However I've just seen there's no stopScanning in my code at all yet. So:
1. What are the consequences? Are some functions impossible to perform in this situation?
2. As the scanning hasn't been stopped, why do the scandetail value returned by getScanDetail doesn't change?

Maybe some additions in the documentation about the prerequisites for each function to be performed would help. I have the very same issue when trying to change the maximum frame rate.

**Comment by nesdnuma** [comment]
Helloooo. No one here?

**Comment by azarraga** [comment]
Hi Nesdnuma, sorry for the delay, I think we missed your last message. In general, it's good practice to call StopScanning after you're done reading the sensor. When you initiate a stop, the firmware does some internal housecleaning and resets itself to prepare for the next API communication session. If you don't explicitly stop scanning and stop communicating with the sensor, the sensor will time out and do this house cleaning internally anyways. Therefore you're OK without the stop scan, but it's a good idea to include a call to stop scan when you're done with sensor communication.
