### ISSUE TITLE
delta_x and delta_y arbitrary

### ISSUE THREAD

**Issue by NothanUmber** [sensel/sensel-api#9]
I am getting unreliable data for delta_x and delta_y.
Sometimes when I start my application the deltas just stay 0. Other times I am getting one delta as always 0, and the other one as a garbage value. And the third variant is where I get garbage values for both deltas. (The state between the three variants stays the same until I restart the application. Which variant I get seems to be randomly determined at program start).

Here two example outputs of read contacts vs corrected contacts (where I calculate the deltas myself by remembering the touch per id from previous frames):

case where delta_x stays always 0 and delta_y is garbage:
mec::SinglePanel::readTouches (corrected deltas): (x: 119.734,y:71.8008,dx:4.01172,dy:0.152344)
mec::SinglePanel::readTouches: (x: 119.734,y:71.8008,dx:0,dy:1.83705e-40,state:CONTACT_MOVE)

case where both delta_x and delta_y always stay at 0:
mec::SinglePanel::readTouches (corrected deltas): (x: 152.293,y:61.9453,dx:2.16016,dy:0.539062)
mec::SinglePanel::readTouches: (x: 152.293,y:61.9453,dx:0,dy:0,state:CONTACT_MOVE)

snippet of the code that reads the contacts:
bool frameRetrievedState = senselGetFrame(handle_, frameData_);
            for(int current_contact = 0; current_contact < frameData_->n_contacts; ++current_contact) {
                unsigned int state = frameData_->contacts[current_contact].state;
                float x = frameData_->contacts[current_contact].x_pos;
                float x_delta = frameData_->contacts[current_contact].delta_x;
                float y = frameData_->contacts[current_contact].y_pos;
                float y_delta = frameData_->contacts[current_contact].delta_y;
                float z = frameData_->contacts[current_contact].total_force;
                float z_delta = frameData_->contacts[current_contact].delta_force;

**Comment by AlexSensel** [comment]
Hello, thank you for posting this issue. I can see a couple potential answers to this questions:

1) Have you turned on CONTACT_MASK_DELTAS using senselSetContactsMask? By default only ellipses and the default data (x, y, force, area, id, and state are sent. You can enable the additional fields using this method. We understand this might not be clear and will make sure to update the documentation.
2) Make sure you are reading all available frames. You can do so by using senselGetNumAvailableFrames.

**Comment by NothanUmber** [comment]
Hi, thanks a lot for the feedback!
I indeed didn't set the CONTACT_MASK_DELTAS flag. Now I get deltas. But these are way smaller than the ones I am measuring myself (as the difference between previous and current (x,y) coordinates). E.g.:
mec::SinglePanel::readTouches(my deltas): (id:0,x: 167.023,y:46.3945,dx:9.49609,dy:1.66797,state:CONTACT_MOVE)
mec::SinglePanel::readTouches(deltasfrom frame): (id:0,x: 167.023,y:46.3945,dx:2.66016,dy:0.324219,state:CONTACT_MOVE)

I am using senselGetNumAvailableFrames and iterate through all frames I get. But perhaps the rest of the code takes too long the next time I ask for frames some are already overwritten again? Are the deltas calculated based on the frames the API user really retrieved or relative to those that he could have retrieved (if he would have been fast enough)?

**Comment by AlexSensel** [comment]
Hmm, it should calculate deltas off the frames that are retrieved and should be maintained if you do not read frames. We will look into this further. Thank you for reporting the issue.

**Comment by AlexSensel** [comment]
Hello, I looked into this further and I have a couple of updates that should help explain this behavior.
1) I was wrong in my last comment, if you miss frames then the delta will not be maintained. Our reasoning was that the delta could be used as a velocity that is independent of which frames you happen to read.
2) I forgot to mention that to read multiple frames, you should enable the Buffer Control (http://guide.sensel.com/api_adv/#buffer-control and http://guide.sensel.com/sensel_h/index.html#//apple_ref/c/func/senselSetBufferControl). This should help you capture additional frames.

**Comment by NothanUmber** [comment]
Thanks, that explains it. Will look into the buffer control thing (if my application is categorically too slow this won't help presumably, because it can never catch up and thus would fill up the buffer in an instant. But I'll certainly give it a try!)

Have written a small test:
https://github.com/TheTechnobear/MEC/blob/morph/mec-api/devices/morph/panels/tests/t_read_contacts.cpp

When pausing for up to 5 milliseconds between reading all available frames the deltas I calculate (m) are the same as the deltas I read from the morph API (o):
mec::SinglePanel::readTouches(m): (id:0,x: 123.703,y:30.6484,dx:0.242188,dy:0.21875,dz:-8.625,state:CONTACT_MOVE)
mec::SinglePanel::readTouches(o): (id:0,x: 123.703,y:30.6484,dx:0.242188,dy:0.21875,dz:-8.625,state:CONTACT_MOVE)

When pausing for 6 millisecond I sometimes get the same deltas and sometimes not (seems to be the boundary).

And when pausing for 7 milliseconds or more it is completely off:
mec::SinglePanel::readTouches(m): (id:0,x: 158.457,y:45.207,dx:9.98828,dy:0.816406,dz:-19.875,state:CONTACT_MOVE)
mec::SinglePanel::readTouches(o): (id:0,x: 158.457,y:45.207,dx:5.19141,dy:0.492188,dz:-12.5,state:CONTACT_MOVE)

Not much of a problem for delta_x and delta_y - but delta_z is more troublesome as I have no way to calculate this myself...
Will have to have a look whether I can get my full event loop below 5 ms.
Having an option to get (other?) deltas between the current and the last frame read could be highly helpful though for applications with higher workloads. (Alternatively the API user would have to decouple the reading of frames into an own thread (so it doesn't miss a frame) and calculating the deltas between times where the slow thread retrieves frame information in that fast thread.)
